# This OpenAPI specification has been modified and does not comply fully to the actual definitions
# provided by the 3GPP organization
openapi: 3.0.1
info:
    description:
        "OAS 3.0.1 definition of the File Data Reporting MnS Â© 2021, 3GPP Organizational\
        \ Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved."
    title: File Data Reporting MnS
    version: 17.1.0
externalDocs:
    description: 3GPP TS 28.532; Generic management services
    url: http://www.3gpp.org/ftp/Specs/archive/28_series/28.532/
servers:
    - url: "{MnSRoot}/fileDataReportingMnS/{MnSVersion}"
      variables:
          MnSRoot:
              default: http://localhost:8080
              description: See clause 4.4.3 of TS 32.158
          MnSVersion:
              default: v1
              description: Version number of the OpenAPI definition
paths:
    /files:
        get:
            description:
                "Information about available files is read with HTTP GET. The files\
                \ for which information shall be returned are identified with the path component\
                \ (base resource) and the query component (fileDataType, beginTime, endTime)\
                \ of the URI."
            operationId: filesGET
            tags:
                - Files
            parameters:
                - description: This parameter selects files based on the file data type.
                  explode: true
                  in: query
                  name: fileDataType
                  required: true
                  schema:
                      $ref: "#/components/schemas/FileDataType"
                  style: form
                - description:
                      This parameter selects files based on the earliest time they
                      became available
                  explode: true
                  in: query
                  name: beginTime
                  required: false
                  schema:
                      $ref: "#/components/schemas/DateTime"
                  style: form
                - description:
                      This parameter selects files based on the latest time they became
                      available
                  explode: true
                  in: query
                  name: endTime
                  required: false
                  schema:
                      $ref: "#/components/schemas/DateTime"
                  style: form
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                items:
                                    $ref: "#/components/schemas/FileInfo"
                                type: array
                    description:
                        '''Success case ("200 OK"). The resources identified in the
                        request for retrieval are returned in the response message body.'''
                default:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/ErrorResponse"
                    description: Error case.
            summary: Read information about available files
            # x-eov-operation-handler: controllers/DefaultController
        post:
            summary: Create a single file report
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/AddFile"
            operationId: filesPOST
            tags:
                - Files
            responses:
                "201":
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/FileInfoCreated"
                    description: '''Success case ("201 Created"). The resource has been successfully created.'''
                default:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/ErrorResponse"
                    description: Error case.
            # x-eov-operation-handler: controllers/FilesController
    /files/{fileId}:
        get:
            operationId: filesGETById
            parameters:
                - in: path
                  name: fileId
                  required: true
                  schema:
                      type: string
            tags:
                - Files
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                description: |
                                    This data type shall contain key value pairs of the file,
                                    which doesn't follow a specific schema, along with file
                                    metadata packed in the fileInfo attribute.
                                type: object
                                additionalProperties: true
                                properties:
                                    fileInfo:
                                        $ref: "#/components/schemas/FileInfo"
                                required:
                                    - fileInfo
                                example:
                                    host: Zabbix Server
                                    hostid: 1089
                                    fileInfo:
                                        fileLocation: "127.0.0.1:8080/fileDataReportingMnS/v1/files/655bd98833942badb5ff2c91"
                                        fileDataType: Performance
                                        fileReadyTime: 2023-10-30T00:00:00+01:00
                    description:
                        '''Success case ("200 OK"). The resources identified in the
                        request for retrieval are returned in the response message body.'''
                "404":
                    description: A file with specified ID was not found.
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/ErrorResponse"
                            example:
                                error:
                                    errorInfo: "file with id: 655be08d3dbcdd08f5728483 not found"
                default:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/ErrorResponse"
                    description: Error case.
            summary: Get a file by ID
            # x-eov-operation-handler: controllers/FilesController
        delete:
            operationId: filesDELETE
            parameters:
                - in: path
                  name: fileId
                  required: true
                  schema:
                      type: string
            tags:
                - Files
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                description: |
                                    This data type shall contain key value pairs of the file,
                                    which doesn't follow a specific schema, along with file
                                    metadata packed in the fileInfo attribute.
                                type: object
                                additionalProperties: true
                                properties:
                                    fileInfo:
                                        $ref: "#/components/schemas/FileInfo"
                                required:
                                    - fileInfo
                                example:
                                    host: Zabbix Server
                                    hostid: 1089
                                    fileInfo:
                                        fileLocation: "127.0.0.1:8080/fileDataReportingMnS/v1/files/655bd98833942badb5ff2c91"
                                        fileDataType: Performance
                                        fileReadyTime: 2023-10-30T00:00:00+01:00
                    description:
                        '''Success case ("200 OK"). The resource identified in the
                        request for deletion is returned in the response message body.'''
                "404":
                    description: A file with specified ID was not found.
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/ErrorResponse"
                            example:
                                error:
                                    errorInfo: "file with id: 655be08d3dbcdd08f5728483 not found"
                default:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/ErrorResponse"
                    description: Error case.
            summary: Delete a file by ID
    /files/create_many:
        post:
            summary: Create many file reports
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            items:
                                $ref: "#/components/schemas/AddFile"
                            type: array
                            minItems: 1
            operationId: filesPOSTMany
            tags:
                - Files
            responses:
                "201":
                    content:
                        application/json:
                            schema:
                                description: An array containing the created file IDs.
                                type: array
                                items:
                                    type: string
                                minItems: 1
                                example: [fileId1, fileId2, fileId3]

                    description: '''Success case ("201 Created"). The resource has been successfully created.'''
                default:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/ErrorResponse"
                    description: Error case.
            # x-eov-operation-handler: controllers/FilesController
    /subscriptions:
        post:
            callbacks:
                notifyFileReady:
                    "{request.body#/consumerReference}":
                        post:
                            operationId: notifyFileReady_request_bodyConsumerReferencePost
                            requestBody:
                                content:
                                    application/json:
                                        schema:
                                            $ref: "#/components/schemas/NotifyFileReady"
                                required: true
                            responses:
                                "204":
                                    description:
                                        Success case ("204 No Content"). The notification is
                                        successfully delivered. The response message body is absent.
                                default:
                                    content:
                                        application/json:
                                            schema:
                                                $ref: "#/components/schemas/ErrorResponse"
                                    description: Error case.
                            x-callback-request: true
                notifyFilePreparationError:
                    "{request.body#/consumerReference}":
                        post:
                            operationId: notifyFilePreparationError_request_bodyConsumerReferencePost
                            requestBody:
                                content:
                                    application/json:
                                        schema:
                                            $ref: "#/components/schemas/NotifyFilePreparationError"
                                required: true
                            responses:
                                "204":
                                    description:
                                        Success case ("204 No Content"). The notification is
                                        successfully delivered. The response message body is absent.
                                default:
                                    content:
                                        application/json:
                                            schema:
                                                $ref: "#/components/schemas/ErrorResponse"
                                    description: Error case.
                            x-callback-request: true
            description:
                To create a subscription the representation of the subscription
                is POSTed on the /subscriptions collection resource.
            operationId: subscriptionsPOST
            tags:
                - Subscriptions
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/Subscription"
                required: true
            responses:
                "201":
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Subscription"
                    description:
                        Success case ("201 Created"). The representation of the newly
                        created subscription resource shall be returned.
                    headers:
                        Location:
                            description: URI of the newly created subscription resource
                            explode: false
                            required: true
                            schema:
                                type: string
                            style: simple
                default:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/ErrorResponse"
                    description: Error case.
            summary: Create a subscription
            # x-eov-operation-handler: controllers/DefaultController
    /subscriptions/{subscriptionId}:
        get:
            operationId: getSubscription
            parameters:
                - in: path
                  name: subscriptionId
                  required: true
                  schema:
                      type: string
            tags:
                - Subscriptions
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Subscription"
                    description:
                        '''Success case ("200 OK"). The resources identified in the
                        request for retrieval are returned in the response message body.'''
                "404":
                    description: A subscription with specified ID was not found.
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/ErrorResponse"
                            example:
                                error:
                                    errorInfo: "subscription with id: 655be08d3dbcdd08f5728483 not found"
                default:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/ErrorResponse"
                    description: Error case.
            summary: Get a subscription by ID
            # x-eov-operation-handler: controllers/FilesController
        delete:
            description:
                The subscription is deleted by deleting the corresponding subscription
                resource. The resource to be deleted is identified with the path component
                of the URI.
            operationId: subscriptionsSubscriptionIdDELETE
            parameters:
                - description: Identifies the subscription to be deleted.
                  explode: false
                  in: path
                  name: subscriptionId
                  required: true
                  schema:
                      type: string
                  style: simple
            tags:
                - Subscriptions
            responses:
                "204":
                    description:
                        Success case ("204 No Content"). The subscription resource
                        has been deleted. The response message body is absent.
                default:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/ErrorResponse"
                    description: Error case.
            summary: Delete a subscription
            # x-eov-operation-handler: controllers/DefaultController
components:
    schemas:
        FileDataType:
            enum:
                - Performance
                - Trace
                - Analytics
                - Proprietary
            type: string
        FileNotificationTypes:
            enum:
                - notifyFileReady
                - notifyFilePreparationError
            type: string
        FileInfo:
            example:
                fileSize: 0
                fileLocation: fileLocation
                fileReadyTime: 2000-01-23T04:56:07.000+00:00
                fileFormat: fileFormat
                fileDataType: "Performance"
                fileExpirationTime: 2000-01-23T04:56:07.000+00:00
                fileCompression: fileCompression
            properties:
                fileLocation:
                    type: string
                fileSize:
                    $ref: "#/components/schemas/FileSize"
                fileReadyTime:
                    format: date-time
                    type: string
                fileExpirationTime:
                    format: date-time
                    type: string
                fileCompression:
                    type: string
                fileFormat:
                    type: string
                fileDataType:
                    $ref: "#/components/schemas/FileDataType"
            type: object
            required:
                - fileLocation
                - fileReadyTime
                - fileDataType
        NotifyFileReady:
            allOf:
                - $ref: "#/components/schemas/NotificationHeader"
                - $ref: "#/components/schemas/NotifyFileReady_allOf"
        NotifyFilePreparationError:
            allOf:
                - $ref: "#/components/schemas/NotificationHeader"
                - $ref: "#/components/schemas/NotifyFilePreparationError_allOf"
        DateTime:
            description: The date format shall be compliant with RFC3339.
            format: date-time
            type: string
            example: 2023-10-30T00:00:00+01:00
            # https://datatracker.ietf.org/doc/html/rfc3339#section-5.6
        ErrorResponse:
            description:
                Default schema for the response message body in case the request
                is not successful.
            properties:
                error:
                    $ref: "#/components/schemas/ErrorResponse_error"
            type: object
        Subscription:
            example:
                filter:
                    fileContent:
                        hostid: "10084"
                    fileDataType: "Performance"
                    endTime: "2023-10-30T00:00:00+01:00"
                timeTick: 0
                consumerReference: consumerReference
            properties:
                consumerReference:
                    description: Reference (address) of the MnS consumer to which the notifications shall be sent.
                    type: string
                    format: uri
                    # https://stackoverflow.com/questions/3809401/what-is-a-good-regular-expression-to-match-a-url
                    pattern: 'https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()@:%_\+.~#?&//=]*)'
                    example: "127.0.0.1:8080/callback"
                timeTick:
                    description: Initial value of a timer held by the MnS producer. This value defines the time window within which the MnS consumer intends to invoke the "subscribe" operation again to confirm its subscription. The value "0" shall indicate infinity. In this case the subscription is not terminated by the MnS producer. Unit is minutes
                    type: integer
                filter:
                    # description: The filter format shall be compliant to XPath 1.0.
                    $ref: "#/components/schemas/Filter"
            type: object
            required:
                - consumerReference
        NotificationHeader:
            properties:
                href:
                    type: string
                notificationId:
                    type: integer
                notificationType:
                    $ref: "#/components/schemas/NotificationType"
                eventTime:
                    format: date-time
                    type: string
                systemDN:
                    type: string
            required:
                - eventTime
                - href
                - notificationId
                - notificationType
                - systemDN
            type: object
        NotificationId:
            type: integer
        NotificationType:
            oneOf:
                - $ref: "#/components/schemas/AlarmNotificationTypes"
                - $ref: "#/components/schemas/CmNotificationTypes"
                - $ref: "#/components/schemas/PerfNotificationTypes"
                - $ref: "#/components/schemas/HeartbeatNotificationTypes"
                - $ref: "#/components/schemas/FileNotificationTypes"
        # SystemDN:
        #     type: string
        Filter:
            description: The filter format is a free-form JSON object.
            type: object
            additionalProperties: true
            example:
                beginTime: 2000-01-23T04:56:07.000+00:00
                endTime: 2000-01-24T00:00:00+00:00
                fileContent:
                    hostid: "10084"
                fileSize: 20
                fileFormat: fileFormat
                fileDataType: Performance
                fileExpirationTime: 2000-01-23T04:56:07.000+00:00
                fileCompression: fileCompression

        AlarmNotificationTypes:
            enum:
                - notifyNewAlarm
                - notifyChangedAlarm
                - notifyChangedAlarmGeneral
                - notifyAckStateChanged
                - notifyCorrelatedNotificationChanged
                - notifyComments
                - notifyClearedAlarm
                - notifyAlarmListRebuilt
                - notifyPotentialFaultyAlarmList
            type: string
        CmNotificationTypes:
            enum:
                - notifyMOICreation
                - notifyMOIDeletion
                - notifyMOIAttributeValueChanges
                - notifyMOIChanges
            type: string
        PerfNotificationTypes:
            enum:
                - notifyThresholdCrossing
            type: string
        HeartbeatNotificationTypes:
            enum:
                - notifyHeartbeat
            type: string
        NotifyFileReady_allOf:
            properties:
                fileInfoList:
                    items:
                        $ref: "#/components/schemas/FileInfo"
                    type: array
                additionalText:
                    type: string
            type: object
            required:
                - fileInfoList
            example: null
        NotifyFilePreparationError_allOf:
            properties:
                fileInfoList:
                    items:
                        $ref: "#/components/schemas/FileInfo"
                    type: array
                reason:
                    type: string
                additionalText:
                    type: string
            type: object
            required:
                - fileInfoList
            example: null
        ErrorResponse_error:
            properties:
                errorInfo:
                    type: string
            type: object
        AddFile:
            description: File data and metadata.
            properties:
                fileContent:
                    $ref: "#/components/schemas/FileContent"
                fileSize:
                    $ref: "#/components/schemas/FileSize"
                fileReadyTime:
                    format: date-time
                    type: string
                fileExpirationTime:
                    format: date-time
                    type: string
                fileCompression:
                    type: string
                fileFormat:
                    type: string
                fileDataType:
                    $ref: "#/components/schemas/FileDataType"
            type: object
            required:
                - fileDataType
                - fileContent
                - fileReadyTime
        FileInfoCreated:
            properties:
                fileId:
                    type: string
            type: object
            required:
                - fileId
        FileContent:
            description: This data type doesn't have a specific format. It shall contain the contents of the file.
            type: object
            additionalProperties: true
            example:
                host: Zabbix Server
                hostid: 10084
                "42899":
                    name: CPU utilization
                    data:
                        - itemid: "42899"
                          clock: 1699440883
                          value: 1.4933189999996
                          ns: 597517450
                        - itemid: "42899"
                          clock: 1699440943
                          value: 1.4521909999991
                          ns: 710613952
        FileSize:
            description: The size of the file. Its value is a non negative integer. The unit is byte.
            type: integer
            example: 1024
